<?php

CREATE TABLE `oms_order` (
  `to_id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '运输单序号',
  `to_no` char(32) DEFAULT '' COMMENT '纸质运单编号',
  `to_customer_no` char(190) DEFAULT '' COMMENT '客户单号，客户内部单号',
  `cu_id` int(11) unsigned DEFAULT NULL COMMENT '委托客户序号',
  `cu_no` char(32) DEFAULT NULL COMMENT '委托客户编号',
  `co_id` int(11) unsigned DEFAULT NULL COMMENT '委托人序号',
  `cp_id` int(11) unsigned DEFAULT NULL COMMENT '项目序号',
  `cp_no` char(128) DEFAULT NULL COMMENT '项目编号',
  `to_taketime` int(11) unsigned DEFAULT '0' COMMENT '接单时间',
  `to_type` tinyint(4) unsigned DEFAULT '0' COMMENT '订单类型，0标准运输，1耗材调拨 ，2山东齐鲁订单',
  `to_goodstype` tinyint(4) NOT NULL DEFAULT '0' COMMENT '货物类型（1=血样，2=样本，3=药品）',
  `to_important` tinyint(4) unsigned DEFAULT '0' COMMENT '重要程序，0普通，1重要',
  `to_timelimit` tinyint(4) unsigned DEFAULT '0' COMMENT '运送时限，0：12小时，1：24小时，2：36小时，3：48小时，4：72小时',
  `to_temperature` tinyint(4) unsigned DEFAULT '0' COMMENT '运输温度，1 CW0-30，2 HW15-25，3 HW18-30，4 LB2-8，5 GB-20，6 YD-150',
  `to_temperature_name` varchar(30) DEFAULT NULL COMMENT '运输温度记录',
  `to_thermometer` tinyint(4) unsigned DEFAULT '0' COMMENT '温度计，1无温度计，2生生温度计，3客户温度计，4客户和生生温度计',
  `to_hygrometer` tinyint(4) DEFAULT '0' COMMENT '湿度计，1无湿度计，2生生湿度计，3客户湿度计，4客户和生生湿度计',
  `to_insure` tinyint(4) unsigned DEFAULT '0' COMMENT '是否投保，0否，1是',
  `to_insure_value` decimal(20,2) DEFAULT '0.00' COMMENT '声明价值',
  `to_getcash` tinyint(4) unsigned DEFAULT '0' COMMENT '付款方式，0月结，1发货方现金，2收货方现金',
  `to_invoice` tinyint(4) unsigned DEFAULT '0' COMMENT '是否开票，0否，1是',
  `to_assign_uid` int(11) unsigned DEFAULT '0' COMMENT '指派给用户序号',
  `to_assign_username` char(32) DEFAULT '' COMMENT '指派给用户姓名',
  `start_region_id` int(11) unsigned DEFAULT '0' COMMENT '发件所在地区ID',
  `start_region_name` char(128) DEFAULT NULL COMMENT '发件地区名',
  `start_cu_id` int(11) DEFAULT NULL,
  `start_cu_name` varchar(400) DEFAULT NULL COMMENT '发件客户',
  `start_co_name` varchar(300) DEFAULT NULL COMMENT '发件客户',
  `start_mobile_phone` varchar(180) DEFAULT NULL COMMENT '发件联系手机',
  `start_address` varchar(800) DEFAULT NULL COMMENT '发件联系地址',
  `start_itude` varchar(255) DEFAULT NULL COMMENT '收件地址经纬度',
  `stop_region_id` int(11) unsigned DEFAULT '0' COMMENT '收件所在地区ID',
  `stop_region_name` char(128) DEFAULT NULL COMMENT '收件地区名',
  `stop_cu_id` int(11) DEFAULT NULL,
  `stop_cu_name` varchar(400) DEFAULT NULL COMMENT '收件客户',
  `stop_co_name` varchar(300) DEFAULT NULL COMMENT '收件联系人',
  `stop_mobile_phone` varchar(180) DEFAULT NULL COMMENT '收件联系手机',
  `stop_address` varchar(800) DEFAULT NULL COMMENT '收件联系地址',
  `stop_itude` varchar(255) DEFAULT NULL COMMENT '收件地址经纬度',
  `to_status` tinyint(4) unsigned DEFAULT '0' COMMENT '运输单状态 0新建 1已审核 2已取件 3已发货 4已提货 5已派件 6已反馈 7已取消 8已关闭 9 删除',
  `to_performance_status` char(4) DEFAULT '0000' COMMENT '绩效状态，0000异常投诉索赔奖励',
  `to_settlement_status` tinyint(4) unsigned DEFAULT '0' COMMENT '结算状态，0未结算，1已结算',
  `to_invoice_status` tinyint(4) unsigned DEFAULT '0' COMMENT '开票状态，0未开票，1已开票',
  `to_goods_status` tinyint(4) unsigned DEFAULT '0' COMMENT '货物状态，0货物完好，1货物破损，2货物丢失，3货物超温，4货物延时',
  `to_outbox_status` tinyint(4) unsigned DEFAULT '0' COMMENT '取件结存状态，0未结存，1已结存',
  `to_inbox_status` tinyint(4) unsigned DEFAULT '0' COMMENT '派件结存状态，0未结存，1已结存',
  `to_sign_status` tinyint(4) unsigned DEFAULT '0' COMMENT '签收单据附件状态，0未上传，1已上传',
  `to_temprecord_status` tinyint(4) unsigned DEFAULT '0' COMMENT '温度数据附件状态，0未上传，1已上传',
  `to_email` text COMMENT '联系邮箱',
  `to_remark` longtext COMMENT '客户备注',
  `to_create_uid` int(11) unsigned DEFAULT '0' COMMENT '创建用户序号',
  `to_create_username` char(32) DEFAULT '' COMMENT '创建用户姓名',
  `to_closetime` int(10) unsigned DEFAULT '0' COMMENT '结案时间',
  `to_createtime` int(10) unsigned DEFAULT '0' COMMENT '创建时间',
  `to_lastupdtime` int(10) unsigned DEFAULT '0' COMMENT '最后一次修改时间',
  `to_outbox_out_no` char(32) DEFAULT '' COMMENT '取件结存出库单号',
  `to_outbox_in_no` char(32) DEFAULT '' COMMENT '取件结存入库单号',
  `to_inbox_out_no` char(32) DEFAULT '' COMMENT '派件结存出库单号',
  `to_inbox_in_no` char(32) DEFAULT '' COMMENT '派件结存入库单号',
  `to_nocheck` tinyint(4) unsigned DEFAULT '0' COMMENT '是否不需要审核 1-是 0-否',
  `to_fileurl` varchar(255) DEFAULT NULL COMMENT '太美api附件链接',
  `to_source` tinyint(4) NOT NULL DEFAULT '1' COMMENT '订单来源',
  `changebox` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否完成换箱',
  `to_site_id` int(11) DEFAULT NULL COMMENT '科文斯项目siteId',
  `to_check_status` tinyint(1) NOT NULL DEFAULT '5' COMMENT '客户审核状态（0=未审核，1=一审，2=二审，5=终审）',
  `to_template` tinyint(1) NOT NULL DEFAULT '1' COMMENT '济南脐血库消息推送状态 0-未推送 1-已推送',
  `to_tags` varchar(150) DEFAULT NULL COMMENT '订单标签',
  `cp_tags` varchar(150) DEFAULT NULL COMMENT '项目标签',
  `to_receipt` int(1) unsigned DEFAULT NULL COMMENT '签收类型: 1-本人签收，2-他人代收',
  `to_trequirement` int(1) DEFAULT '0' COMMENT '运输要求 0正常 2专人 3专车',
  `to_temporary` tinyint(1) DEFAULT '0' COMMENT '暂存货类型 0 未暂存  1 已暂存',
  `to_aging_remark` varchar(1024) DEFAULT NULL COMMENT '时效备注',
  `child_start_region_id` int(11) DEFAULT NULL COMMENT '出发城市子级id',
  `child_start_region_name` varchar(255) DEFAULT NULL COMMENT '出发城市子级名称',
  `child_stop_region_id` int(11) DEFAULT NULL COMMENT '到达城市子级id',
  `child_stop_region_name` varchar(255) DEFAULT NULL COMMENT '到达城市子级名称',
  `to_gatt_status` int(4) DEFAULT '0' COMMENT '校准证书状态',
  `oinvennum` varchar(25) DEFAULT NULL COMMENT '暂存编号',
  `to_hygrometer_range` varchar(255) DEFAULT NULL COMMENT '湿度区间',
  `contact_name` varchar(30) DEFAULT NULL COMMENT '委托人姓名',
  `contact_tel` varchar(30) DEFAULT NULL COMMENT '委托人手机号',
  `to_pid` int(11) DEFAULT NULL COMMENT '主单id',
  `to_attributes` int(4) NOT NULL DEFAULT '1' COMMENT '1.普通订单 2.主单 3.子单',
  `to_category` tinyint(1) NOT NULL DEFAULT '1' COMMENT '1正常订单，2仓库发药',
  `colorcar_true` int(2) DEFAULT '0' COMMENT '是否冷藏车派送 0否 1是',
  `to_kpi` tinyint(1) DEFAULT '1' COMMENT 'KPI 1是 2否',
  `to_review_status` int(4) NOT NULL COMMENT '订单复核 1.未复核 2.已复核',
  `to_abnormal_charge_type` tinyint(1) DEFAULT '1' COMMENT '异常收费 1 无异常收费 2 异常收费',
  `bi_id` int(10) unsigned DEFAULT NULL COMMENT '开票客户id',
  `bi_name` varchar(100) DEFAULT NULL COMMENT '开票客户抬头',
  `to_auto_lastupdtime` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '自动更新最后一次修改时间',
  `to_identify` int(4) DEFAULT '0' COMMENT '0普通订单 1臻和合单 2泰琨合单 3九州通合单',
  `transport_type` tinyint(3) unsigned DEFAULT '0' COMMENT '运输类型 0=常规运输  1=临床发运 2=营销样品  3=其他',
  `cod_amount` decimal(20,2) DEFAULT NULL COMMENT '到付金额',
  `cod_way` tinyint(1) DEFAULT NULL COMMENT '到付方式',
  `outsource` int(11) DEFAULT '3' COMMENT '迈迪朗杰外包类型  全外包   4\n取发外包 5\n提派外包 6\n发提派外包 7',
  `to_is_lable` int(1) DEFAULT '1',
  `to_nucleic_acid` tinyint(2) DEFAULT '0' COMMENT '核酸服务 0无需检测，1 人员核酸，2外包装核酸，3药品核酸，4人员抗体检测',
  `order_check_status` tinyint(1) NOT NULL DEFAULT '2' COMMENT '订单审核状态 1待审核 2审核通过',
  `to_business_type` tinyint(4) NOT NULL DEFAULT '0' COMMENT '0正常订单 2仓库发药',
  `to_the_num` tinyint(4) NOT NULL DEFAULT '1' COMMENT '温度计数量',
  `order_project_process` tinyint(4) unsigned NOT NULL DEFAULT '0' COMMENT '订单审核流程记录',
  `is_dtp` tinyint(4) NOT NULL DEFAULT '2' COMMENT '1是DTP2否',
  `to_carrier_type` tinyint(1) NOT NULL DEFAULT '1' COMMENT '承运方式 1生生运输  2非生生运输',
  PRIMARY KEY (`to_id`),
  KEY `cu_id` (`cu_id`),
  KEY `to_customer_no` (`to_customer_no`),
  KEY `start_region_id` (`start_region_id`),
  KEY `to_assign_uid` (`to_assign_uid`),
  KEY `stop_region_id` (`stop_region_id`),
  KEY `to_type` (`to_type`),
  KEY `to_no` (`to_no`),
  KEY `to_create_uid` (`to_create_uid`),
  KEY `to_status` (`to_status`),
  KEY `idx_nuc_acid` (`to_nucleic_acid`),
  KEY `to_temperature` (`to_temperature`),
  KEY `cp_id_index` (`cp_id`),
  KEY `index_to_pid` (`to_pid`),
  KEY `to_auto_lastupdtime` (`to_auto_lastupdtime`),
  KEY `idx_to_createtime` (`to_createtime`) USING BTREE,
  KEY `idx_cp_id` (`cp_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=2110232 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='运输订单表';

CREATE TABLE `oms_logistics` (
  `ol_id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '物流信息序号',
  `to_id` int(11) unsigned DEFAULT '0' COMMENT '运输单序号',
  `ol_pickup_num` tinyint(4) unsigned DEFAULT '0' COMMENT '取件次数',
  `ol_pickup_planbegin` int(10) unsigned DEFAULT '0' COMMENT '预约取件时间',
  `ol_pickup_time` int(10) unsigned DEFAULT '0' COMMENT '取件时间',
  `ol_pickup_person` varchar(1024) DEFAULT NULL COMMENT '取件人，以逗号分隔，具有操作员标识的用户',
  `ol_pickup_name` varchar(1024) DEFAULT NULL COMMENT '取件人 用逗号间隔',
  `ol_goods_quantity` int(10) DEFAULT '0' COMMENT '货物件数',
  `ol_goods_weight` decimal(10,2) DEFAULT '0.00' COMMENT '货物重量（千克）',
  `ol_delivery_num` tinyint(4) unsigned DEFAULT '0' COMMENT '派件次数',
  `ol_delivery_time` int(10) unsigned DEFAULT '0' COMMENT '派件时间',
  `ol_delivery_planbegin` int(10) unsigned DEFAULT '0' COMMENT '预约派件时间',
  `ol_delivery_person` varchar(1024) DEFAULT NULL COMMENT '派件人，以逗号分隔，具有操作员标识的用户',
  `ol_delivery_name` varchar(1024) DEFAULT NULL COMMENT '派件人，用逗号分隔',
  `ol_sign_name` varchar(180) DEFAULT '' COMMENT '签收人',
  `ol_pack_time` int(10) unsigned DEFAULT '0' COMMENT '方案准备时间',
  `ol_createtime` int(10) unsigned DEFAULT '0' COMMENT '创建时间',
  `ol_lastupdtime` int(10) unsigned DEFAULT '0' COMMENT '最后一次修改时间',
  `ol_remark` longtext COMMENT '取派备注',
  `ol_nsso_no` tinyint(2) DEFAULT NULL COMMENT 'nsso配置ID',
  `ol_payer` varchar(255) DEFAULT NULL COMMENT '他人付款--付款人',
  `ol_contact_information` char(50) DEFAULT NULL COMMENT '他人付款--联系方式',
  `ol_document` char(5) DEFAULT NULL COMMENT '随货文件 0-否 1-是',
  `ol_collection_remark` varchar(255) DEFAULT NULL COMMENT '代收原因',
  `ol_pickup_quantity` varchar(255) DEFAULT NULL COMMENT '实取数量',
  `ol_delivery_quantity` varchar(255) DEFAULT NULL COMMENT '实派数量',
  `ol_whether_consistent` int(10) DEFAULT NULL COMMENT '取派是否一致 0-否 1-是',
  `ol_pickup_planend` int(10) DEFAULT '0' COMMENT '预约取件截止时间',
  `ol_delivery_planend` int(11) DEFAULT '0' COMMENT '预约派件截止时间',
  `ol_pickup_planfw` int(2) DEFAULT '0' COMMENT '预约取件范围',
  `ol_delivery_planfw` int(2) DEFAULT '0' COMMENT '预约派件范围',
  `ol_become_time` int(10) unsigned DEFAULT NULL COMMENT '采血时间',
  `ol_static_class` int(11) unsigned DEFAULT NULL COMMENT '客户部门',
  `ol_pack_timeshow` int(10) DEFAULT '0' COMMENT '方案准备时间展示',
  `ol_upload` tinyint(1) DEFAULT '0' COMMENT '交接单据上传配置 0:未上传，1:已上传',
  `ol_hospital` int(10) DEFAULT NULL COMMENT '医院ID',
  `ol_start_hospital` int(10) DEFAULT NULL COMMENT '发件医院ID',
  `ol_tostatus` int(10) DEFAULT '0' COMMENT '时效监控状态: 0:未确认，1:已确认',
  `ol_auto_lastupdtime` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '自动更新最后一次修改时间',
  `ol_unsigned` tinyint(1) DEFAULT '1' COMMENT '签收单据是否签字，0未签字，1已签字',
  `ol_unsigned_status` tinyint(1) DEFAULT '0' COMMENT '签收单据未签字处理状态，0待处理，1已处理',
  `ol_pickup_time_limit` tinyint(1) DEFAULT '0' COMMENT '预取时间限制 1不能晚， 2不能早，3不能早不能晚',
  `ol_delivery_time_limit` tinyint(1) DEFAULT '0' COMMENT '预派时间限制 1不能晚， 2不能早，3不能早不能晚',
  `ol_auto_box_type` varchar(255) DEFAULT NULL COMMENT '计划箱型',
  `central_patient_number` int(11) NOT NULL DEFAULT '0' COMMENT '中心患者人数',
  `ol_transport_status` tinyint(2) NOT NULL DEFAULT '2' COMMENT '客户端运输状态，默认 2待确认，枚举ol_transport_status',
  `experiment_id` int(11) NOT NULL DEFAULT '0' COMMENT '试验中心ID 关联customer_experiment cex_id',
  PRIMARY KEY (`ol_id`),
  KEY `ol_auto_lastupdtime` (`ol_auto_lastupdtime`),
  KEY `ol_pickup_time` (`ol_pickup_time`),
  KEY `ol_delivery_time` (`ol_delivery_time`),
  KEY `to_id` (`to_id`),
  KEY `ol_pickup_planbegin` (`ol_pickup_planbegin`)
) ENGINE=InnoDB AUTO_INCREMENT=394899 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='运输订单物流信息表';




CREATE TABLE `customer` (
  `cu_id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '客户序号',
  `cu_no` char(32) DEFAULT '' COMMENT '客户编号',
  `cu_name` char(255) DEFAULT '' COMMENT '客户名称',
  `cu_tel` char(16) DEFAULT '' COMMENT '客户电话',
  `cu_fax` char(20) DEFAULT '' COMMENT '客户传真',
  `cu_url` char(128) DEFAULT NULL COMMENT '客户网址',
  `region_id` int(11) unsigned DEFAULT '0' COMMENT '地区ID',
  `region_name` char(128) DEFAULT NULL COMMENT '地区名',
  `cu_add` char(128) DEFAULT '' COMMENT '客户地址',
  `manage_region_id` int(11) DEFAULT NULL COMMENT '管辖城市id',
  `cu_lat` varchar(15) DEFAULT NULL COMMENT '百度坐标',
  `cu_lng` varchar(15) DEFAULT NULL COMMENT '百度坐标',
  `ct_id` smallint(6) unsigned DEFAULT '0' COMMENT '行业类型',
  `cu_maysize` tinyint(4) unsigned DEFAULT '0' COMMENT '潜在规模 0 超0万 1 超1万 2 超5万 3 超20万 4 超50万',
  `cu_nowsize` tinyint(4) unsigned DEFAULT '0' COMMENT '合作规模 0 超0万 1 超1万 2 超5万 3 超20万 4 超50万',
  `em_id` int(11) unsigned DEFAULT NULL COMMENT '客户发展业务员员工序号',
  `em_name` char(32) DEFAULT '' COMMENT '客户发展业务员员工姓名',
  `cu_relation` tinyint(4) unsigned DEFAULT '0' COMMENT '客户关系 0潜在 1洽谈 2合作 3无效',
  `cu_expiretime` int(10) unsigned DEFAULT '0' COMMENT '合同到期日期',
  `balance` decimal(10,2) DEFAULT '0.00' COMMENT '账户余额，单位分',
  `cu_status` tinyint(4) unsigned DEFAULT '0' COMMENT '客户状态 0启用，1禁用',
  `cu_remark` varchar(1024) DEFAULT NULL COMMENT '备注',
  `cu_createtime` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '创建时间',
  `cu_lastupdtime` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '最后一次修改时间',
  `at_id` varchar(10) NOT NULL DEFAULT '' COMMENT '附件ID，只保留一个',
  `cu_visible` tinyint(1) unsigned DEFAULT '1' COMMENT '状态 1正常，0删除',
  `emp_id` int(11) DEFAULT NULL COMMENT '项目专员ID',
  `emp_name` char(32) DEFAULT NULL COMMENT '项目专员名称',
  `emc_id` int(11) DEFAULT NULL COMMENT '结算专员ID',
  `emc_name` char(32) DEFAULT NULL COMMENT '结算专员姓名',
  `ar_id` int(11) DEFAULT NULL COMMENT '所属大区ID',
  `is_importent` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否精益客户',
  `cu_feedback_type` tinyint(2) DEFAULT '1' COMMENT '是否接收自动反馈 1 接收 2 不接收',
  `cu_type` tinyint(2) DEFAULT '1' COMMENT '审核状态 1 待审核 2 已审核',
  `goods_size_type` int(1) DEFAULT '1' COMMENT '货物状态: 1-关闭，2-启用',
  `auto_rem_mess` int(1) DEFAULT '0' COMMENT '自动催款:0-开启,1-关闭',
  `cu_temperature_type` tinyint(4) DEFAULT '1' COMMENT '温度批量上传   1 开启 2 关闭',
  `cu_projectorder` tinyint(3) unsigned DEFAULT '2' COMMENT '1=客户立项 2=没有立项 3=项目立项',
  `cg_id` int(10) DEFAULT NULL COMMENT '集团id',
  `cu_level` tinyint(4) DEFAULT NULL COMMENT '客户级别 参考globaltype customer_level',
  `cu_knot_type` tinyint(4) DEFAULT NULL COMMENT '结算类型 参考globaltype knot_type',
  `cu_sign_feedback` tinyint(4) DEFAULT '1' COMMENT '代签短信提醒  1开启 2关闭',
  `cu_piece_feedback` tinyint(4) DEFAULT '2' COMMENT '签收自动反馈 1开启 2关闭',
  `cu_temperature_feedback` tinyint(4) DEFAULT '2' COMMENT '温度自动反馈 1开启 2关闭',
  `cu_class` tinyint(1) DEFAULT '0' COMMENT '是否开启部门选择',
  `cu_upload` tinyint(1) DEFAULT '0' COMMENT '交接单据上传配置 0:关闭，1：开启',
  `cu_hospital` tinyint(1) DEFAULT '0' COMMENT 'CRA、CRC下单，发件地址绑定医院地址 0:关闭，1：开启',
  `cu_goods_print` tinyint(1) unsigned DEFAULT '0' COMMENT '打印运单时将货物名称打印在运单上',
  `cu_take_contact` tinyint(1) unsigned DEFAULT NULL COMMENT '推送取件人联系方式',
  `cu_take_email` tinyint(1) DEFAULT NULL COMMENT '抄送邮件',
  `cu_template` tinyint(1) DEFAULT '0' COMMENT '客户配置使用中文模板 0：默认不使用  1；使用',
  `cu_upload_print` tinyint(1) DEFAULT '0' COMMENT '客户端上传excel批量打印运单  0：关闭 1：使用',
  `cu_doc_audit` tinyint(3) unsigned DEFAULT '0' COMMENT 'CRA 上传交接单据，药品管理员审核  0不用审核  1需要审核',
  `cu_send_message` tinyint(3) unsigned DEFAULT '1' COMMENT '是否发送取派短信 1发送 0不发送',
  `cu_auto_lastupdtime` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '自动更新最后一次修改时间',
  `cu_center_manage` tinyint(3) unsigned DEFAULT '0' COMMENT '是否勾选中心管理 1是 0否',
  `cu_configure_center` tinyint(3) unsigned DEFAULT '0' COMMENT '可配置试验中心  1可以配置 0不可配置',
  `receive_unit_match` tinyint(3) unsigned DEFAULT '0' COMMENT '0否 1是',
  `receive_unit_match_key` varchar(100) DEFAULT NULL COMMENT '收件单位匹配关键字',
  `cu_print_express_remark` tinyint(3) unsigned DEFAULT '0' COMMENT '客户单号打印到运单备注',
  `cu_customer_no` tinyint(1) DEFAULT '0' COMMENT '下单可填写客户单号  0：否  1：是',
  `cu_tengsen_trmperature` tinyint(1) DEFAULT '2' COMMENT '不支持批量上传滕森温度数据  1 不支持   2 支持  ',
  `cu_create_account_email` tinyint(1) DEFAULT '0' COMMENT '开通账号发送通知邮件  1 发送  0 不发送 ',
  `cu_bind_project_email` tinyint(1) DEFAULT '0' COMMENT '绑定项目发送通知邮件  1 发送  0 不发送  ',
  `cu_debit` tinyint(1) DEFAULT '0' COMMENT '欠款客户  0不是   1是',
  `stock_warning_sms` tinyint(1) DEFAULT '0' COMMENT '库存预警短信推送 1 发送  0 不发送',
  `cma_id` int(11) DEFAULT NULL COMMENT '销售助理ID',
  `cma_name` char(32) DEFAULT NULL COMMENT '销售助理姓名',
  `feedback_type` varchar(255) DEFAULT NULL,
  `cu_create_username` char(32) DEFAULT NULL COMMENT '客户创建人',
  `cu_create_uid` int(11) DEFAULT NULL COMMENT '客户创建人ID',
  `drug_customer_config` tinyint(4) DEFAULT '1' COMMENT '客户选药配置  1关闭 2开启',
  `cu_important` char(12) DEFAULT NULL COMMENT '客户重要性',
  `cu_grade` tinyint(4) DEFAULT NULL COMMENT '客户重要等级',
  `cu_segment` tinyint(4) DEFAULT '0' COMMENT '业务板块',
  `wechat_drug_customer_config` tinyint(4) DEFAULT '1' COMMENT '微信客户选药配置  1关闭 2开启',
  `is_email_intercept` tinyint(1) NOT NULL DEFAULT '2' COMMENT '是否邮件拦截 1拦截 2不拦截',
  `clinical_orders_split_create` tinyint(1) NOT NULL DEFAULT '1' COMMENT '临床订单分开创建 1关闭 2开启',
  PRIMARY KEY (`cu_id`),
  UNIQUE KEY `cu_no` (`cu_no`),
  KEY `ct_id` (`ct_id`),
  KEY `em_id` (`em_id`),
  KEY `cu_expiretime` (`cu_expiretime`),
  KEY `cu_id` (`cu_id`),
  KEY `cu_name` (`cu_name`),
  KEY `region_id` (`region_id`),
  KEY `manage_region_id` (`manage_region_id`),
  KEY `cu_auto_lastupdtime` (`cu_auto_lastupdtime`),
  KEY `idx_cgid` (`cg_id`)
) ENGINE=InnoDB AUTO_INCREMENT=2019005890 DEFAULT CHARSET=utf8 COMMENT='客户表';



CREATE TABLE `customer` (
  `cu_id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '客户序号',
  `cu_no` char(32) DEFAULT '' COMMENT '客户编号',
  `cu_name` char(255) DEFAULT '' COMMENT '客户名称',
  `cu_tel` char(16) DEFAULT '' COMMENT '客户电话',
  `cu_fax` char(20) DEFAULT '' COMMENT '客户传真',
  `cu_url` char(128) DEFAULT NULL COMMENT '客户网址',
  `region_id` int(11) unsigned DEFAULT '0' COMMENT '地区ID',
  `region_name` char(128) DEFAULT NULL COMMENT '地区名',
  `cu_add` char(128) DEFAULT '' COMMENT '客户地址',
  `manage_region_id` int(11) DEFAULT NULL COMMENT '管辖城市id',
  `cu_lat` varchar(15) DEFAULT NULL COMMENT '百度坐标',
  `cu_lng` varchar(15) DEFAULT NULL COMMENT '百度坐标',
  `ct_id` smallint(6) unsigned DEFAULT '0' COMMENT '行业类型',
  `cu_maysize` tinyint(4) unsigned DEFAULT '0' COMMENT '潜在规模 0 超0万 1 超1万 2 超5万 3 超20万 4 超50万',
  `cu_nowsize` tinyint(4) unsigned DEFAULT '0' COMMENT '合作规模 0 超0万 1 超1万 2 超5万 3 超20万 4 超50万',
  `em_id` int(11) unsigned DEFAULT NULL COMMENT '客户发展业务员员工序号',
  `em_name` char(32) DEFAULT '' COMMENT '客户发展业务员员工姓名',
  `cu_relation` tinyint(4) unsigned DEFAULT '0' COMMENT '客户关系 0潜在 1洽谈 2合作 3无效',
  `cu_expiretime` int(10) unsigned DEFAULT '0' COMMENT '合同到期日期',
  `balance` decimal(10,2) DEFAULT '0.00' COMMENT '账户余额，单位分',
  `cu_status` tinyint(4) unsigned DEFAULT '0' COMMENT '客户状态 0启用，1禁用',
  `cu_remark` varchar(1024) DEFAULT NULL COMMENT '备注',
  `cu_createtime` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '创建时间',
  `cu_lastupdtime` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '最后一次修改时间',
  `at_id` varchar(10) NOT NULL DEFAULT '' COMMENT '附件ID，只保留一个',
  `cu_visible` tinyint(1) unsigned DEFAULT '1' COMMENT '状态 1正常，0删除',
  `emp_id` int(11) DEFAULT NULL COMMENT '项目专员ID',
  `emp_name` char(32) DEFAULT NULL COMMENT '项目专员名称',
  `emc_id` int(11) DEFAULT NULL COMMENT '结算专员ID',
  `emc_name` char(32) DEFAULT NULL COMMENT '结算专员姓名',
  `ar_id` int(11) DEFAULT NULL COMMENT '所属大区ID',
  `is_importent` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否精益客户',
  `cu_feedback_type` tinyint(2) DEFAULT '1' COMMENT '是否接收自动反馈 1 接收 2 不接收',
  `cu_type` tinyint(2) DEFAULT '1' COMMENT '审核状态 1 待审核 2 已审核',
  `goods_size_type` int(1) DEFAULT '1' COMMENT '货物状态: 1-关闭，2-启用',
  `auto_rem_mess` int(1) DEFAULT '0' COMMENT '自动催款:0-开启,1-关闭',
  `cu_temperature_type` tinyint(4) DEFAULT '1' COMMENT '温度批量上传   1 开启 2 关闭',
  `cu_projectorder` tinyint(3) unsigned DEFAULT '2' COMMENT '1=客户立项 2=没有立项 3=项目立项',
  `cg_id` int(10) DEFAULT NULL COMMENT '集团id',
  `cu_level` tinyint(4) DEFAULT NULL COMMENT '客户级别 参考globaltype customer_level',
  `cu_knot_type` tinyint(4) DEFAULT NULL COMMENT '结算类型 参考globaltype knot_type',
  `cu_sign_feedback` tinyint(4) DEFAULT '1' COMMENT '代签短信提醒  1开启 2关闭',
  `cu_piece_feedback` tinyint(4) DEFAULT '2' COMMENT '签收自动反馈 1开启 2关闭',
  `cu_temperature_feedback` tinyint(4) DEFAULT '2' COMMENT '温度自动反馈 1开启 2关闭',
  `cu_class` tinyint(1) DEFAULT '0' COMMENT '是否开启部门选择',
  `cu_upload` tinyint(1) DEFAULT '0' COMMENT '交接单据上传配置 0:关闭，1：开启',
  `cu_hospital` tinyint(1) DEFAULT '0' COMMENT 'CRA、CRC下单，发件地址绑定医院地址 0:关闭，1：开启',
  `cu_goods_print` tinyint(1) unsigned DEFAULT '0' COMMENT '打印运单时将货物名称打印在运单上',
  `cu_take_contact` tinyint(1) unsigned DEFAULT NULL COMMENT '推送取件人联系方式',
  `cu_take_email` tinyint(1) DEFAULT NULL COMMENT '抄送邮件',
  `cu_template` tinyint(1) DEFAULT '0' COMMENT '客户配置使用中文模板 0：默认不使用  1；使用',
  `cu_upload_print` tinyint(1) DEFAULT '0' COMMENT '客户端上传excel批量打印运单  0：关闭 1：使用',
  `cu_doc_audit` tinyint(3) unsigned DEFAULT '0' COMMENT 'CRA 上传交接单据，药品管理员审核  0不用审核  1需要审核',
  `cu_send_message` tinyint(3) unsigned DEFAULT '1' COMMENT '是否发送取派短信 1发送 0不发送',
  `cu_auto_lastupdtime` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '自动更新最后一次修改时间',
  `cu_center_manage` tinyint(3) unsigned DEFAULT '0' COMMENT '是否勾选中心管理 1是 0否',
  `cu_configure_center` tinyint(3) unsigned DEFAULT '0' COMMENT '可配置试验中心  1可以配置 0不可配置',
  `receive_unit_match` tinyint(3) unsigned DEFAULT '0' COMMENT '0否 1是',
  `receive_unit_match_key` varchar(100) DEFAULT NULL COMMENT '收件单位匹配关键字',
  `cu_print_express_remark` tinyint(3) unsigned DEFAULT '0' COMMENT '客户单号打印到运单备注',
  `cu_customer_no` tinyint(1) DEFAULT '0' COMMENT '下单可填写客户单号  0：否  1：是',
  `cu_tengsen_trmperature` tinyint(1) DEFAULT '2' COMMENT '不支持批量上传滕森温度数据  1 不支持   2 支持  ',
  `cu_create_account_email` tinyint(1) DEFAULT '0' COMMENT '开通账号发送通知邮件  1 发送  0 不发送 ',
  `cu_bind_project_email` tinyint(1) DEFAULT '0' COMMENT '绑定项目发送通知邮件  1 发送  0 不发送  ',
  `cu_debit` tinyint(1) DEFAULT '0' COMMENT '欠款客户  0不是   1是',
  `stock_warning_sms` tinyint(1) DEFAULT '0' COMMENT '库存预警短信推送 1 发送  0 不发送',
  `cma_id` int(11) DEFAULT NULL COMMENT '销售助理ID',
  `cma_name` char(32) DEFAULT NULL COMMENT '销售助理姓名',
  `feedback_type` varchar(255) DEFAULT NULL,
  `cu_create_username` char(32) DEFAULT NULL COMMENT '客户创建人',
  `cu_create_uid` int(11) DEFAULT NULL COMMENT '客户创建人ID',
  `drug_customer_config` tinyint(4) DEFAULT '1' COMMENT '客户选药配置  1关闭 2开启',
  `cu_important` char(12) DEFAULT NULL COMMENT '客户重要性',
  `cu_grade` tinyint(4) DEFAULT NULL COMMENT '客户重要等级',
  `cu_segment` tinyint(4) DEFAULT '0' COMMENT '业务板块',
  `wechat_drug_customer_config` tinyint(4) DEFAULT '1' COMMENT '微信客户选药配置  1关闭 2开启',
  `is_email_intercept` tinyint(1) NOT NULL DEFAULT '2' COMMENT '是否邮件拦截 1拦截 2不拦截',
  `clinical_orders_split_create` tinyint(1) NOT NULL DEFAULT '1' COMMENT '临床订单分开创建 1关闭 2开启',
  PRIMARY KEY (`cu_id`),
  UNIQUE KEY `cu_no` (`cu_no`),
  KEY `ct_id` (`ct_id`),
  KEY `em_id` (`em_id`),
  KEY `cu_expiretime` (`cu_expiretime`),
  KEY `cu_id` (`cu_id`),
  KEY `cu_name` (`cu_name`),
  KEY `region_id` (`region_id`),
  KEY `manage_region_id` (`manage_region_id`),
  KEY `cu_auto_lastupdtime` (`cu_auto_lastupdtime`),
  KEY `idx_cgid` (`cg_id`)
) ENGINE=InnoDB AUTO_INCREMENT=2019005890 DEFAULT CHARSET=utf8 COMMENT='客户表';